---
- name: Install required packages for web server
  yum:
    name:
      - httpd
      - php
      - php-mysqlnd
      - wget
    state: present

- name: Start and enable Apache
  service:
    name: httpd
    state: started
    enabled: yes